Repository ZEviod/Personal-finance-management, pull requests merged in 2024-10, with the labels that each got.

#1 Base-setup
  README.md
  backend/app/__init__.py
  backend/model/ml_model.py
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/app/favicon.ico
  frontend/app/fonts/GeistMonoVF.woff
  frontend/app/fonts/GeistVF.woff
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/assets/index.ts
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/constants/data.ts
  frontend/helpers/index.ts
  frontend/lib/utils.ts
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 Base Ui for intraction
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/assets/index.ts
  frontend/components/AddTransaction.tsx
  frontend/components/Balance.tsx
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/components/IncomeExpense.tsx
  frontend/components/Layout.tsx
  frontend/components/Transaction.tsx
  frontend/components/TransaxctionList.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement, good first issue, hacktoberfest-accepted

#9 Fix #7: Contact Us Page added
  frontend/app/contact/page.tsx
  frontend/app/layout.tsx
Labels: documentation, hacktoberfest-accepted, Front-End
